### ISSUE TITLE
signTextJS plus not working with Firefox 50.0beta

### ISSUE THREAD

**Issue by dessyv** [jasp00/signTextJS#1]
Hello, it seems that signTextJS plus 0.8.5 is not working with Firefox 50.0beta. It gives "TypeError" (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type). 
Also it is not working with Firefox 51.0a2 (2016-10-09) (32 bits). It gives "signtextjsplus:Error: Invalid argument" and "signtextjsplus:TypeError: domWindow.crypto is undefined".

**Comment by jasp00** [comment]
Waiting for feedback from Firefox BTS: https://bugzilla.mozilla.org/show_bug.cgi?id=1309690

**Comment by jasp00** [comment]
The first problem is fixed since signTextJS plus 0.8.6. The second part is related to Electrolysis, so I will close this issue in favor of #3.
