### ISSUE TITLE
native backend doesn't work, ubuntu 16.04

### ISSUE THREAD

**Issue by slesru** [jasp00/signTextJS#11]
Installed it:

sh ./signtextjs_plus-0.9.0-x86_64-linux-gnu.run 
Verifying archive integrity... All good.
Uncompressing signTextJS plus  100%  
Installing to /usr/lib/mozilla/native-messaging-hosts

restarted firefox, all I get is window with text:

signText running...
Please consider using signTextAsync.

Close this window when signing has finished.

and OK button.

Thank you!

**Comment by jasp00** [comment]
What happens when you click the OK button?

**Comment by slesru** [comment]
Window with message became closed and bank's web interface says that there was error signing document.

**Comment by jasp00** [comment]
Please go to the add-on preferences and enable "Debug to console". Open the Browser Console and clear it. Try to sign again and report the Browser Console messages.

**Comment by slesru** [comment]
this._recipeManager is null  LoginManagerParent.jsm:86
Error: WebExtension context not found!  ExtensionParent.jsm:821:13
stderr output from native app signtextjs_plus: /usr/lib/mozilla/native-messaging-hosts/signtextjs_plus: error while loading shared libraries: libjsoncpp.so.0: cannot open shared object file: No such file or directory
File closed  NativeMessaging.jsm:192
SignText: Native back end disconnected

So I have no  libjsoncpp.so.0 in my system, as I can see I have only  libjsoncpp.so.1, sorry have no time to try something- have go to work right now :-(

**Comment by slesru** [comment]
OK, tried to symlink   ln -s libjsoncpp.so.1 libjsoncpp.so.0
Then I have crash. Looks like I need to compile from sources, binaries are not Ubuntu 16.04 compatible.
Thank you!

**Comment by jasp00** [comment]
Could you try again with the installer for version 0.9.1-rc2 at [releases](https://github.com/jasp00/signTextJS/releases)?

**Comment by slesru** [comment]
Hello!

Now I get blank window with moz-extention header.
Browser console says:

getRecipes: falling back to a synchronous message for: "https://x509-online.bystrobank.ru"  LoginRecipes.jsm:244
this._recipeManager is null  LoginManagerParent.jsm:86
TypeError: invalid 'in' operand browser[Подробнее]  tabbrowser.xml:2426:1
TypeError: can't access dead object[Подробнее] tab.js:1646:1

Thank you!

**Comment by jasp00** [comment]
What happens if you right click on the blank window? Does a context menu appear?

**Comment by slesru** [comment]
Hello!

Tried this again, may be I did not completely restarted firefox before, now , after system reboot, it works!
Thank you!

**Comment by slesru** [comment]
Oh, no! I tried this again- I need to right click in blank window, then it became filled up with info, and everything works.
So, as you wrote, right click...

**Comment by jasp00** [comment]
The blank page issue is being handled at [Mozilla BTS](https://bugzilla.mozilla.org/show_bug.cgi?id=1428352).

**Comment by slesru** [comment]
Thank you!
