### ISSUE TITLE
Doesnt work with Firefox 57 64bit/ Ubuntu 16.04

### ISSUE THREAD

**Issue by radolin** [jasp00/signTextJS#12]
Hello, 

I have an installation with Firefox 57 and Ubuntu 16.04. When I attempt to sing something I get a pop-up saying "signText running... Please consider using signTextAsync. [ОК]" but nothing else. If I click OK it appears again. After I click OK a second time my bank's website says 'certificate error'.

I've installed the native-messaging-hosts bridge into my .mozilla directory. 

On the same machine, under a different user with Firefox ESR and the old SignTextJS extension signing works, so my base reader/smartcard setup should be OK.

Any help will be appreciated and thanks for he hard work!

Rado

**Comment by radolin** [comment]
I saw the other issue with the empty window and the right click/resize workaround, but I don't get any window, even an empty one.

**Comment by radolin** [comment]
I saw the other issue with the empty window and the right click/resize workaround, but I don't get any window at all, not even an empty one. Nothing is shown in debug console, even though I enabled it in the settings.

The only meaningful error I managed to get to is 'error:noMatchingCert' returned by the the native binary. It is communicating with the smart card reader, as I see the LED blink when I press the 'Sign' button, but for some reason doesn't like/find my certificate.

**Comment by jasp00** [comment]
Could you download `test/html/test.html`, open the test page, and press the `signText` button?

**Comment by radolin** [comment]
Besides my bank's website, I used this for local testing with the same effect: https://github.com/Glamdring/js-signer

I tried your test.html from master. SignText gives the same in the result box: error:noMatchingCert

SignTextAsync does nothing and I get this in the console: 
SignText: DataCloneError: The object could not be cloned.  common.js:14:3

I compiled the test.cpp and run it, and it succeeds, but seems it's not using the smartcard.

Is there an easy way to test the signtextjs_plus bridge separately, without the browser, but actually using my smartcard and e-signature?

**Comment by jasp00** [comment]
>Is there an easy way to test the signtextjs_plus bridge separately, without the browser, but actually using my smartcard and e-signature?

The way is not easy: you could tweak `test.cpp` and pass your profile directory in `test/linux/runtest`. Since you know how to compile, I think it would be easy for you to debug with the browser. Do you know how to compile and use the native back end?

You should try the following in `signtextjs_plus.cpp`:
1. Use `log()` or `std::cerr` statements to debug `get_user_certs`.
2. In the call to `CERT_FindUserCertsByUsage`, switch the 4th parameter to `PR_FALSE` to allow invalid certificates.

**Comment by radolin** [comment]
I set the 4th parameter to PR_FALSE, but there is no difference, same  error:noMatchingCert.

I inserted a log("debug test") message in the get_user_certs() function, but I don't get anything in the browser console. Even removed the if (s_debug), but no difference. If I run the test from the console using your runtest script my "debug test" message gets printed to stderr. 

My understanding is that I should be seeing this message in the browser console, but may be I'm missing something.

**Comment by jasp00** [comment]
Are you sure you are using the new executable? What happens if you run:
`ls -l ~/.mozilla/native-messaging-hosts/signtextjs_plus-bin`
?

**Comment by radolin** [comment]
Yes, I'm running make inside your source dir and after that manually copying the new executable to ~/.mozilla/native-messaging-hosts/

In the signtextjs_plus shell script I redirected the stderr of signtextjs_plus-bin to a file. Now after using test.hrml I can see the log messages there and can confirm that the call to CERT_FindUserCertsByUsage returns null.

Any pointers on useful prints I can add to help debug this?

**Comment by jasp00** [comment]
A symlink would avoid the manual copy. Browser console should display stderr.

I think I should take over, but you may want to try this instead of `CERT_FindUserCertsByUsage`:
`PK11_ListCerts(PK11CertListAll, NULL);`

**Comment by jasp00** [comment]
I have reproduced the problem. Could you try current `signtextjs_plus.cpp` in master?

**Comment by radolin** [comment]
I can sign the message now, but the interaction is a bit weird.

1. I press the sign button
2. The 'signText running...Please consider using signTextAsync' pop up appears
3. The new window to choose certificate, enter PIN code, etc. appears
4. I type the PIN code and press OK, but nothing happens
5. If I close the window manually and then press OK on the pop-up the signing actually happens

Thank you very much for the assistance! Let me know if you need any more testing/help from my side.

**Comment by jasp00** [comment]
Version 0.9.3 is released. Form interaction is fixed; let me know if this is not the case.

**Comment by svetoslav80** [comment]
Version 0.9.3 is not working for me. I'm also getting this: ""signText running... Please consider using signTextAsync. [ОК]" and then "no certificate was found" messagebox. Firefox 60.0b2 (64-bit) , Ubuntu 17.10
