### ISSUE TITLE
0.9.3 , wrong list of certificates

### ISSUE THREAD

**Issue by slesru** [jasp00/signTextJS#13]
Hello!

We have 2 certificates, and one of them will expire soon, so bank issued new certificate for us.
I installed it into firefox 58 and can successfully login into bank's web interface using it , and I removed old certificate from firefox.
But when I try sign I see two certificates in list, one of which is old certificate and no new certificate, so signing is not possible.
This certificate works with old version of extension in firefox esr.
btw, new certificate has CN Name. TWYRV1f5@gUAAQzo3Kg 2018-01-26  , i.e. have some random data in it and name 
while old one has user name and issuer info in it and no date.
but, anyway, this does not explain why old and removed certificate is still listed...

Thank you!

**Comment by jasp00** [comment]
Firefox 58 introduces changes in certificate management. Could you try a fresh Firefox profile (back up the existing one first), import your certificates, and test?

**Comment by jasp00** [comment]
Firefox does not update its certificate database on disk immediately. Restarting Firefox should workaround this problem.

**Comment by jasp00** [comment]
>Could you try a fresh Firefox profile (back up the existing one first), import your certificates, and test?

Your current version will not work with the new database. Do you know how to compile the native back end? If not, I will prepare a pre-release.

**Comment by jasp00** [comment]
Version 0.9.4-rc1 is available.

**Comment by slesru** [comment]
Hello!

Sorry for late reply- too busy today for reading mail...
Unfortunately, 0.9.4rc1 has the same issue, I'll try on fresh profile asap.

Thank you!

**Comment by slesru** [comment]
Oops! 
Sorry, I forgot that I installed not only system-wide , but, by mistake, to my home directory too.

0.9.4rc1 works! 

Thank you very much!
