### ISSUE TITLE
Donations to the project

### ISSUE THREAD

**Issue by jasp00** [jasp00/signTextJS#15]
Users have asked about donations. PayPal does not support GitHub organizations, thus this project cannot accept donations. However, you can donate to the Mozilla Foundation mentioning this project.

You may donate [here](https://www.paypal.com/cgi-bin/webscr?business=donate@mozilla.org&cmd=_donations&item_name=Donation+to+the+Mozilla+Foundation&item_number=https://addons.mozilla.org/addon/signtextjs-plus).

**Comment by radolin** [comment]
Just made a small donation, thanks for your hard work! I'm using the plug-in for some time now and besides the UI glitches (due to Firefox bugs) all is working fine!

**Comment by heliokom** [comment]
Congratulations on your work. I made a small donation citing the project.
