### ISSUE TITLE
SignText: Unknown encoding 'windows-1251'

### ISSUE THREAD

**Issue by boris-petrov** [jasp00/signTextJS#16]
I'm trying to use the latest version (0.9.3) but I'm getting a popup with the text:

```
signText running...
Please consider using signTextAsync.

Close this window when signing has finished.
```

When I click OK, nothing happens and the that error message is in the console:

`SignText: Unknown encoding 'windows-1251'`

Am I doing something wrong?

P.S. Using Firefox ESR version 52.5.3 (64-bit).

**Comment by jasp00** [comment]
Popup is normal. I have added support for windows-1251. Be aware that I do not test on Firefox 52 anymore. Open `test/html/test.html` to check the signature result.

**Comment by kajo23** [comment]
I have the same problem.

I see in console:
unreachable code after return statement [Learn more]
ClientScriptA.js:2782:28
SignText: Unknown encoding 'windows-1251'

PS Using Firefox 59.0.3 (32-bit)

**Comment by jasp00** [comment]
Version 0.9.4 supports windows-1251.
