### ISSUE TITLE
Problem after upgrade to Firefox 59

### ISSUE THREAD

**Issue by celyo** [jasp00/signTextJS#17]
After update to Firefox 59 a message windows is displayed every time I'm trying to sign an order, and nothing else happened(certificate choose dialog is not displayed). 

This is the message text:

```
signText running...
Please consider using signTextAsync.

Close this window when signing has finished.
```
P.S. I'm using Firefox 59 on openSUSE Leap 42.3 x64.

**Comment by jasp00** [comment]
Version 0.9.4 handles new SQLite databases, which is relevant to upgrades (https://github.com/jasp00/signTextJS/issues/13). Please reopen this issue if upgrades to Firefox 60 fail.
