### ISSUE TITLE
Library not loaded: /usr/local/opt/jsoncpp/lib/libjsoncpp.19.dylib

### ISSUE THREAD

**Issue by minfrin** [jasp00/signTextJS#19]
After installing the native signtextjs_plus application v0.9.5 on MacOS Mojave, an attempt to sign causes a crash as below.

Dyld Error Message:
  Library not loaded: /usr/local/opt/jsoncpp/lib/libjsoncpp.19.dylib
  Referenced from: /Library/Application Support/Mozilla/*/signtextjs_plus
  Reason: image not found

The signtextjs_plus binary has been bound to a private copy of libjsoncpp, which is not available / not installed as part of the install.

To fix this, the extension needs to depend on a JSON library available natively on MacOS.

**Comment by jasp00** [comment]
What is your native JSON library?

**Comment by minfrin** [comment]
No idea to be honest. I went hunting for the canonical JSON library on MacOS and got lost in all the noise of other APIs that accept JSON.

I've been ripping apart this code in the chrome-token-signing nativemessaging API to see if I could get some clues, but I'm struggling on mapping the code to the APIs being used:

https://github.com/open-eid/chrome-token-signing/blob/6e9b4c84d1511226205fba7b62aa7a2caaad58a6/host-osx/chrome-host.mm#L99

**Comment by jasp00** [comment]
You should run `brew install jsoncpp nss`; I will update the how-to. I cannot test the DMG, but I guess you cannot execute files inside a DMG.

**Comment by minfrin** [comment]
In my case I have macports already installed, so trying to install brew at the same time will cause chaos.

Ideally this code should use the native JSON library provided by MacOS, and not a third party one.

**Comment by jasp00** [comment]
With MacPorts, does `sudo port install jsoncpp nss` work? I could assist in developing a Portfile if someone steps up as the port maintainer; see the [guide](https://guide.macports.org/).

**Comment by minfrin** [comment]
The following hack workaround exists to ensure the libraries aren't missing:

Little-Net:plist minfrin$ sudo port install jsoncpp nss

Little-Net:~ root# mkdir -p /usr/local/opt/jsoncpp/lib/
Little-Net:~ root# ln -s /opt/local/lib/libjsoncpp.19.dylib /usr/local/opt/jsoncpp/lib/libjsoncpp.19.dylib
Little-Net:~ root# mkdir -p /usr/local/opt/nspr/lib
Little-Net:~ root# ln -s /opt/local/lib/nspr/libnspr4.dylib /usr/local/opt/nspr/lib/libnspr4.dylib
Little-Net:~ root# mkdir -p /usr/local/opt/nss/lib
Little-Net:~ root# ln -s /opt/local/lib/nss/libnss3.dylib /usr/local/opt/nss/lib/libnss3.dylib
Little-Net:~ root# ln -s /opt/local/lib/nss/libsmime3.dylib /usr/local/opt/nss/lib/libsmime3.dylib

**Comment by jasp00** [comment]
These required libraries are embedded in current installer for macOS. Continuous integration confirms that the modified back end works. Thus, this issue is fixed.
