### ISSUE TITLE
need version 0.8.7

### ISSUE THREAD

**Issue by vegetzo** [jasp00/signTextJS#21]
Dear Developers,

Please provide the old 0.8.7 version for manual install so that old browser versions like firefox 45.9 ESR can install it. I need it because the proprietary signing solution I use needs java applet and java applet under linux firefox is supported only in old version of FF

Regards,
vegetzo

**Comment by jasp00** [comment]
Source code for version 0.8.7 is available at branch `add-on-sdk`.

**Comment by jasp00** [comment]
Here is the [add-on](https://github.com/jasp00/signTextJS/files/5250259/signtextjs_plus-0.8.7-fx.xpi.zip) released by Mozilla.

**Comment by jasp00** [comment]
Documentation has been updated. This issue is solved.
