### ISSUE TITLE
crypto.signTextAsync() call is undocumented

### ISSUE THREAD

**Issue by minfrin** [jasp00/signTextJS#22]
The crypto.signTextAsync() call is not formally documented anywhere.

According to the code, the function defintion is as follows:

function signTextAsync(text, options, resolve, ...CAs)

- From the code, text is a string.
- What data type is options? What are valid options? What are their defaults?
- What is "resolve"? It appears to be a function of some kind, what is it for, and what does it do?
- CAs... the list of CAs. Are these strings? What is the behaviour if this list is empty?

**Comment by minfrin** [comment]
In the case of resolve, this is the callback function with the response of the attempt to sign.

**Comment by jasp00** [comment]
This function is documented now.
