### ISSUE TITLE
Excessively vague error: error:noMatchingCert

### ISSUE THREAD

**Issue by minfrin** [jasp00/signTextJS#24]
When the web extension returns a list of certs, and the certificate list is empty, the response code error:noMatchingCert is returned.

This message is can be caused by the following scenarios:

- The web extension has picked up certs in the wrong NSS directory and the directory is empty.
- The correct NSS directory is empty.
- The correct NSS directory contains certificates, but the usages are not accepted.
- The correct NSS directory contains certificates, but they are expired or not valid yet.
- The correct NSS directory contains certificates, but do not match an unspecified non_repudiation criteria.
- The correct NSS directory contains certificates, but the certificate cannot be matched to a CA.
- The correct NSS directory contains certificates, but the certificate does not have the email signer key usage,.

The message error:noMatchingCert is too vague to be useful, and end users have no meaningful symptoms they can describe to technical support other than "the list is empty", nor can technical support help without bringing the code up in a debugger.

To fix this, the full list of certificates need to be returned, along with a description of whether the given certificate is valid, and if invalid, why it is invalid. The UI needs to give the option to view invalid certificates, with some kind of tooltip or other mechanism to indicate why the certificate is not a candidate to be selected.

**Comment by jasp00** [comment]
There is a new preference to use invalid certificates. The reason for rejection is included in certificate details.
