### ISSUE TITLE
error:internalError returned from sign_text() with nothing logged

### ISSUE THREAD

**Issue by minfrin** [jasp00/signTextJS#25]
When attempting to sign some text using signTestJS+ 0.9.5 on MacOS Mojave and Firefox 60ESR, we enter the code here:

https://github.com/jasp00/signTextJS/blob/23dfaaacdc4d02c1ed859f9d1c95fcc906746c71/src/signtextjs_plus.cpp#L284

Somehow we leave this code without logging any messages to the browser log.

Looking inside the code, we have two code paths that leave the function with an error but don't log anything:

https://github.com/jasp00/signTextJS/blob/23dfaaacdc4d02c1ed859f9d1c95fcc906746c71/src/signtextjs_plus.cpp#L360

https://github.com/jasp00/signTextJS/blob/23dfaaacdc4d02c1ed859f9d1c95fcc906746c71/src/signtextjs_plus.cpp#L406

We also have a variable called s_debug that could, if set to false, suppress all error messages:

https://github.com/jasp00/signTextJS/blob/23dfaaacdc4d02c1ed859f9d1c95fcc906746c71/src/signtextjs_plus.cpp#L45

**Comment by jasp00** [comment]
The two mentioned code paths are logged now.
