### ISSUE TITLE
Addon not in Firefox after running Linux installer 

### ISSUE THREAD

**Issue by aenchevich** [jasp00/signTextJS#27]
This is the contents of the native-messaging-hosts dir:

aenchevich@pc ~$ ls -l ~/.mozilla/native-messaging-hosts/
total 172
-rw------- 1 aenchevich aenchevich 129632 Jul 10  2018 libjsoncpp.so.0
-rwx------ 1 aenchevich aenchevich    174 Jul 10  2018 signtextjs_plus
-rwx------ 1 aenchevich aenchevich  31720 Jul 10  2018 signtextjs_plus-bin
-rw------- 1 aenchevich aenchevich    237 May  9 17:17 signtextjs_plus.json

However the "about:addons" page says "You don't have any add-ons of this type installed"

And this is the first few lines in "about:support" :

Name 	Firefox
Version 	60.6.3esr
Build ID 	20190507003026
Update History 	
Update Channel 	esr
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
OS 	Linux 4.11.8-300.fc26.x86_64

**Comment by jasp00** [comment]
The installer only installs the native back end. The add-on is at the Firefox Add-ons [page](https://addons.mozilla.org/en-US/firefox/addon/signtextjs-plus/).

**Comment by aenchevich** [comment]
I see... 
Well the problem was that I was having problem using signTextJS plus and so I thought I'd get the version from github (instead of the one from the link).

At any rate I did have at one point both the backend and the signTextJS plus addon installed and nevertheless was getting errors and was not able to sign documents,

**Comment by jasp00** [comment]
It looks like this issue is solved.
