### ISSUE TITLE
Verificar formato firma

### ISSUE THREAD

**Issue by miq25** [jasp00/signTextJS#30]
Buenos días,

hay alguna manera de poder ver la estructura de la firma resultante del pkcs7 base 64

muchas gracias

saludos

**Comment by jasp00** [comment]
La manera habitual en aplicaciones servidoras es usando una API adecuada, como GnuTLS. También puedes usar esta orden con la firma sin Base64:
```
derdump -i signature.der
```
O esta:
```
openssl cms -inform der -in signature.der -cmsout -print
```

**Comment by miq25** [comment]
Hola,

Gracias por la información.

¿Se podría poner el atributo S/MIME ?

Lo digo porque si el plugin es una continuidad de la firma del netscape veo que el netscape tenía la estructura del siguiente enlace

https://docs.oracle.com/cd/E19957-01/816-6152-10/contents.htm#1029050

Muchas gracias.

Saludos

**Comment by miq25** [comment]
Hola,

 ¿sería posible contactar contigo vía email por ejemplo para comentarte poder hacer modificaciones personalizadas en el código.?

Muchas gracias

saludos

**Comment by jasp00** [comment]
> ¿Se podría poner el atributo S/MIME ?

Se podría, pero no veo razón para hacerlo.

> Lo digo porque si el plugin es una continuidad de la firma del netscape

No, es una continuación de la firma de Firefox.

> ¿sería posible contactar contigo vía email por ejemplo para comentarte poder hacer modificaciones personalizadas en el código.?

La gente contacta conmigo vía correo por muchos motivos; respondo a veces.

**Comment by miq25** [comment]
Hola,

bien es que necesito este campo en la firma para que pase unas validaciones
en un sistema externo al mio.
Utilizo el código que tu continuas desarrollando ya que me parece una buena
opción para el desarrollo que hago y por eso te pregunto si podrías poner
el atributo como personalización.

Te pedía el correo para poder hablarlo más abiertamente y poder contribuir
en el desarrollo económico del proyecto.

muchas gracias por tu atención

Saludos

**Comment by jasp00** [comment]
> necesito este campo en la firma para que pase unas validaciones en un sistema externo al mio.

Parece que ese sistema externo no soporta la firma de Firefox desde hace más de 15 años, si es que alguna vez la ha soportado. Uno de los problemas que veo es que exigir un atributo de capacidad S/MIME no es práctica estándar. Necesitaría saber más sobre ese sistema externo y por qué debes usarlo.

**Comment by miq25** [comment]
Hola Javier,

parece que no, pero me gustaría añadir ese campo para que la soportara.

No es nada estandard aunque tengo poca información de cómo está montado
este sistema externo.

mi email es miquelllam@gmail.com si te parece bien me envias un correo y
hablamos por ese canal y te explico como es el sistema.

muchas gracias

saludos

**Comment by jasp00** [comment]
- La documentación recoge cómo verificar e inspeccionar firmas.
- El atributo de capacidad S/MIME no es necesario.
- La consulta privada ha sido atendida.

Esta cuestión está resuelta.
