### ISSUE TITLE
ff53 - Rows in the list of certificates are empty

### ISSUE THREAD

**Issue by sharapanoff** [jasp00/signTextJS#6]
![ff53](https://cloud.githubusercontent.com/assets/10178310/25284862/09e032e0-26c1-11e7-9863-af367927ca4b.png)

it is related to [857627](https://bugzilla.mozilla.org/show_bug.cgi?id=857627)
and will be fixes by #4

**Comment by jasp00** [comment]
Version 0.8.7 is still in the review queue.

**Comment by sharapanoff** [comment]
sorry - i saw that the pull request is open, but didn't check the list of commits  to see that you have already fixed it
