### ISSUE TITLE
can choose signing certificate

### ISSUE THREAD

**Issue by slesru** [jasp00/signTextJS#7]
Firefox 53.0 ,  certificates list is empty.

SignTextJS  ( without plus) works fine though.

**Comment by jasp00** [comment]
>SignTextJS ( without plus) works fine though.

Thank you for the information. This is because @mozkeeler works at Mozilla. signTextJS 0.7.7 was released on April 25 and it is already available at AMO, whereas signTextJS plus 0.8.7 was released on April 14 and it is still at position 200/287 in the review queue.

**Comment by ousia** [comment]
@jasp00, I wonder whether it would make sense to join efforts with @mozkeeler in a single project.

**Comment by jasp00** [comment]
>I wonder whether it would make sense to join efforts

https://github.com/mozkeeler/signTextJS/pull/39#issuecomment-210647007

**Comment by ousia** [comment]
@jasp00, I see now why my proposal doesn’t make any sense.

I’m trying to get a digital certificate at [FNTM-RCM](https://www.sede.fnmt.gob.es/certificados/persona-fisica/obtener-certificado-con-dnie/solicitar-certificado). I’m on Fedora 53 and I get an error in the request submission.

Is there a way to get the XPI file before it has been approved for release?

**Comment by jasp00** [comment]
>Is there a way to get the XPI file before it has been approved for release?

If you are using Firefox 48 or later, you cannot run unsigned XPI files. There should be a way to run the unpacked file, but I do not know how; you should ask Fedora maintainers. If you build from source, `jpm run` allows you to use the add-on with a temporary profile; you may get the FNMT certificate, but remember to export it to disk.

(158/288 in the review queue)

**Comment by jasp00** [comment]
Version 0.8.7 was finally published.
