### ISSUE TITLE
Firefox 57 support

### ISSUE THREAD

**Issue by pcambra** [jasp00/signTextJS#8]
Will there be support for Firefox 57 in this plugin?
The mozkeeler version has stated that there won't be: https://github.com/mozkeeler/signTextJS/issues/49#issuecomment-297165905
However this is marked as required by the FNMT: http://www.cert.fnmt.es/documents/10445900/10528353/solicitud_certificado_persona_fisica.pdf

Thanks

**Comment by jasp00** [comment]
>Will there be support for Firefox 57 in this plugin?

It is my intention to support it. However, bear in mind that I am a political prisoner. I am locked in the madhouse for more than six months already. I barely have time to use my computer. So, I will implement this as soon as I am allowed.

**Comment by jasp00** [comment]
Version 0.9.0 supports Firefox 57 on Linux. The extension requires a native back end. Windows and macOS ones are requested at https://github.com/jasp00/signTextJS/issues/9 and https://github.com/jasp00/signTextJS/issues/10. I am closing this issue.
